### ISSUE TITLE
Make argon support VSC Beta

### ISSUE THREAD

**Issue by RealMrCactus** [argon-rbx/argon#16]
Title says it all

**Comment by DervexHero** [comment]
Hey, this repo no longer contains Visual Studio Code extension source code.

If you want Argon 1 (legacy) to support VSC Beta please create issue [here](https://github.com/argon-rbx/argon-legacy) but keep in mind that I'm no longer working on this version as it's obsolete.

If you want Argon 2 (latest) to support VSC Beta please create issue [here](https://github.com/argon-rbx/argon-vscode) however I haven't even started working on the new extension because I'm working on the CLI now.
