### ISSUE TITLE
Argon uses wrong project.json when using a multi-place setup

### ISSUE THREAD

**Issue by EthanMichalicek** [argon-rbx/argon#23]
While testing Argon 2 for usability for my team, I ran into an issue when setting up more than one `.project.json` file. Our two files are `Town.project.json` and `Track.project.json`, pictured here.

<img width="1510" alt="image" src="https://github.com/argon-rbx/argon/assets/51338441/bd3d991d-62cd-4ebd-ab67-875601a873d0">

When running the Town project with `argon run Town.project.json`, everything works fine. When running the Track project file, however, everything appears to work correctly, except that it mirrors what's in the Town file instead. At first, I thought it was due to Argon just not picking up the correct file, but the Argon Roblox plugin was picking up the "Track" project name. So I went back and ran `argon sourcemap Track.project.json` and found out what is going on. The `filePaths` property generated by the sourcemap refers to the Town project file instead of the Track project file, shown below.

<img width="555" alt="image" src="https://github.com/argon-rbx/argon/assets/51338441/2067d2bb-35fc-4b06-b423-d48f04c572e9">

It is probably worth noting two things - first, the Town project file was created before the Track project file. Second, I'm fairly certain we ran Argon once when the Track file did not yet exist. Not sure why, but something seems to have caused it to latch onto the Town project as the "default", and I suspect it could have something to do with either of these steps we took while testing.

**Comment by EthanMichalicek** [comment]
I just saw this after posting this issue; seems likely that it's the same bug?
https://github.com/argon-rbx/argon/discussions/22#discussioncomment-8866550

**Comment by DervexDev** [comment]
Yep that's the same bug. I thought I fixed it but it is slightly more complicated.

Argon middleware processes "child" instances diffrently as it gets first occurence of matching `SyncRule` in the parent directory of that instance. And the project is "child" instance as its `.json` file is located under the main directory and because its file also contains name: `*.project.json` it makes the method I mentioned not work properly.

Even though it is the only exception I'm significantly modifying the middleware right now but as I said the update will be available today.

**Comment by DervexDev** [comment]
Fixed in d38ef21f841cd48cb94ca240c911fbfe7fb18b4c. Available in [2.0.0-pre4](https://github.com/argon-rbx/argon/releases/tag/2.0.0-pre4).

The fix however caused another bug - sourcemap does not include `.src` and `init` files. I'm going to fix this tomorrow.
