### ISSUE TITLE
Add `--async` parameter to `serve`, `build` and `sourcemap` commands

### ISSUE THREAD

**Issue by Aristosis** [argon-rbx/argon#66]
Using `argon serve -- --async` does not free up the console window
Arch via WSL 2

Edit: More information
![image](https://github.com/argon-rbx/argon/assets/161574090/5e46b56c-7c08-4619-b1e3-dbb81a4ff5bc)

https://github.com/argon-rbx/argon/assets/161574090/d72ef510-0937-4a6c-8259-ec0a692fced7

Couldn't find a verbose parameter so this is all I got. Strangely cant find the project file but when specified it works fine(?)
dont mind the wind in the background i was about to jump out the battle bus 😭

**Comment by DervexDev** [comment]
Okay so first of all Argon has no `--async` parameter. To use Argon asynchronously you have to enable [`run_async` setting](https://argon.wiki/docs/configuration#global-config), just run `argon config run_async true`.

Unfortunately, there is currently a problem when running `serve` because I forgot to change one thing that makes Argon run in async mode when I renamed `run` command to `serve` a while back. I'm going to fix this issue today.

But I actually think that `--async` parameter could be a great addition to Argon, do you think we should implement that?

**Comment by Aristosis** [comment]
> Okay so first of all Argon has no `--async` parameter. To use Argon asynchronously you have to enable [`run_async` setting](https://argon.wiki/docs/configuration#global-config), just run `argon config run_async true`.
oopsie. In all honesty I did try the run_async setting before this and it didnt work just like you said. I dont know what lead me to believe that parameter exists. mb 
>
> But I actually think that `--async` parameter could be a great addition to Argon, do you think we should implement that?
Yeah, this is a good idea

Unrelated to this issue, might open another one for it, but what are the details behind how and what kind of instances argon is capable of syncing/replicating?

**Comment by DervexDev** [comment]
See the [File Types](https://argon.wiki/api/file-types) on Argon wiki.

**Comment by DervexDev** [comment]
> Yeah, this is a good idea

Available in [2.0.10](https://github.com/argon-rbx/argon/releases/tag/2.0.10)
